# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.arloesol.eu
title: Arloesol
author: John Arloesol
description: > # "this text appears in head meta for Google search
  IT services and consulting
copyright: 'Copyright &copy; 2019. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/arloesol
  - title: github
    url: https://github.com/arloesol
  - title: linkedin
    url: https://www.linkedin.com/company/arloesol
